name: Build algolib

on:
  push:
    branches: [master]

jobs:
  pdf:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install prerequisities
      run: sudo apt-get update && sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra latexmk python3-pygments
    - name: Build PDF
      run: ./make.sh
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: algolib.pdf
        path: build/algolib.pdf
